### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by popomore** [node-modules/mz-modules#1]
- mz-modules/sleep -> ko-sleep
- mz-modules/mkdirp -> mkdirp
- mz-modules/rimraf-> rimraf
- mz-modules/nexttick-> process.nextTick

**Comment by fengmk2** [comment]
终于来了

**Comment by popomore** [comment]
终于想好名字了

**Comment by nickasam** [comment]
额，老哥，在ts中的没有提示呀~需要自己建一个文件。。。
